# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args:
            - -o requirements.txt
            - --without-hashes
            - --without-urls
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args: # arguments to configure black
            - --line-length=120
            - --exclude="""\.git |
                  \.__pycache__|
                  \.hg|
                  \.mypy_cache|
                  \.tox|
                  \.venv|
                  _build|
                  buck-out|
                  build|
                  dist"""
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
            - --max-line-length=120
            - --exclude=.venv
            - --max-complexity=18
            - --select=B,C,E,F,W,T4,B9
              # these are errors that will be ignored by flake8
              # check out their meaning here
              # https://flake8.pycqa.org/en/latest/user/error-codes.html
            - --ignore=F401,E203,E501,W503
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
            - --profile=black
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
            - --convention=numpy
            - --add-select=D417
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        - --recursive=y
        - --max-line-length=120
        - --include-naming-hint=y
