server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ProjectName
    pipeline_stages:
    - json:
        expressions:
          toplevel_record: record
    - json:
        expressions:
          seclevel_level: level
        source: toplevel_record
    - json:
        expressions:
          internal_level: name
        source: seclevel_level
    - labels:
        level: internal_level
    static_configs:
    - targets:
        - localhost
      labels:
        app: ProjectNameApp
        __path__: ./opt/logs/log.json

#  - job_name: flog_scrape
#    docker_sd_configs:
#      - host: unix:///var/run/docker.sock
#        refresh_interval: 5s
#        filters:
#          - name: label
#            values: ["logging=promtail"]
#    relabel_configs:
#      - source_labels: ['__meta_docker_container_name']
#        regex: '/(.*)'
#        target_label: 'container'
#      - source_labels: ['__meta_docker_container_log_stream']
#        target_label: 'logstream'
#      - source_labels: ['__meta_docker_container_label_logging_jobname']
#        target_label: 'job'